### ISSUE TITLE
How to do this on other cards?

### ISSUE THREAD

**Issue by zerodrama** [ius/radeonvolt#1]
I can't seem to be able to set frequencies on 7970s for example.

**Comment by ius** [comment]
This (rather old) code mmaps the RV8XX i2c controller to access the VT1165 voltage regulator used on 58XX cards.

As such, it indeed won't work for newer cards - making it work would require updating the i2c controller code and adding support for whatever voltage regulator is used on the card in question - which is non-trivial I'm afraid.

**Comment by REELcoder** [comment]
How did you found the needed register level documentation to implement the i2c access. I assume this was not just guessed.

**Comment by ius** [comment]
@REELcoder Correct. A (limited) datasheet, combined with some reverse engineering of a graphics card vendors' overclocking utility.
